version: '2'

services:
    db:
        image: mysql:5.6
        container_name: docker-drupal-mysql
        volumes:
            - ${DATABASE_PATH}:/var/lib/mysql
            - ./mysql/mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3307:3306
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: docker-drupal-php
        volumes:
            - ${DRUPAL_PATH}:/var/www/html
            #- ${DRUPAL_PRIVATE_FILES_PATH}:/var/www/private
            #- ${DRUPAL_PUBLIC_FILES_PATH}/project:/var/www/html/sites/project/files
        ports:
            - 9000:9000
    nginx:
        image: nginx
        container_name: docker-drupal-nginx
        ports:
            - 8080:80
        volumes_from:
            - php
        volumes:
            - ./nginx/default.template.conf:/etc/nginx/conf.d/default.template.conf
            - ${LOGS_PATH}/nginx/:/var/log/nginx
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    elk:
        image: willdurand/elk
        container_name: docker-drupal-elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
